[package]
name = "erasure"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reed-solomon-erasure = {version = "4.0", features = ["simd-accel"]}
fixed-buffer = "0.3.1"